---

downloads: "~/.tmp/ansible-downloads/"
home: "~"

# see the sdkman role https://github.com/Comcast/ansible-sdkman
sdkman_install_packages:
        - { candidate: java}
        - { candidate: gradle}
        - { candidate: maven}

#see the homebrew role https://github.com/geerlingguy/ansible-role-homebrew
homebrew_installed_packages:
  - bash-completion
  - git
  - openssl
  - wget

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - google-backup-and-sync
  - firefox
  - sublime-text
  - skype
  - iterm2
  - intellij-idea
  - docker


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""