---

downloads: "~/.tmp/ansible-downloads/"
home: "~"

homebrew_installed_packages:
  - bash-completion
  - git
  - openssl
  - wget

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - sublime-text
  - skype
  - iterm2
  - intellij-idea

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""