---

downloads: "~/.tmp/ansible-downloads/"
home: "~"

# see the sdkman role https://github.com/Comcast/ansible-sdkman
sdkman_install_packages:
        - { candidate: java, version: '11.0.2-open' }
        - { candidate: gradle, version: '5.2.1' }
        - { candidate: maven, version: '3.6.0'}

#see the homebrew role https://github.com/geerlingguy/ansible-role-homebrew
homebrew_installed_packages:
  - bash-completion
  - git
  - openssl
  - wget

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - google-backup-and-sync
  - sublime-text
  - skype
  - iterm2
  - intellij-idea
  - docker


# See the role https://github.com/geerlingguy/ansible-role-mas
mas_installed_apps: []
mas_email: ""
mas_password: ""