---

downloads: "~/.tmp/ansible-downloads/"
home: "~"

# see the sdkman role https://github.com/Comcast/ansible-sdkman
sdkman_install_packages:
        - { candidate: java, version: '' }
        - { candidate: gradle, version: '' }
        - { candidate: maven, version: '' }

#see the homebrew role https://github.com/geerlingguy/ansible-role-homebrew
homebrew_installed_packages:
  - bash-completion
  - git
  - openssl
  - wget
  - python

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - google-backup-and-sync
  - sublime-text
  - skype
  - iterm2
  - intellij-idea
  - docker


# See the role https://github.com/geerlingguy/ansible-role-mas
mas_installed_apps: []
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []