---
- hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
#    - debug: msg="{{ ansible_pkg_mgr }}"

    # update the default.config.yml variables with ones from config.yml if it exists
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    # https://github.com/geerlingguy/ansible-role-homebrew
    - role: geerlingguy.homebrew
      when: configure_homebrew
      tags: ['homebrew']
    # https://github.com/geerlingguy/ansible-role-mas
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    # https://github.com/Comcast/ansible-sdkman
    - role: comcast.sdkman
      when: configure_sdkman
      tags: ['sdkman']
    # https://github.com/viasite-ansible/ansible-role-zsh
    - role: viasite-ansible.zsh
      when: configure_zsh
      tags: ['zsh']



  tasks:
    - include_tasks: tasks/ansible-check.yml

    - include_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - include_tasks: tasks/ssh.yml
      when: configure_ssh
      tags: ['ssh']

    - include_tasks: tasks/zsh.yml
      when: (configure_zsh && configure_dotfiles)
      tags: ['zsh', 'dotfiles']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"