---
# Copy files from my configs repository.
# Use when you don't want local changes to be saved in the configs repo
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
    force: yes
  become: false

- name: Copy dotfiles into home folder.
  copy:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item | basename }}"
    force: yes
  become: false
  with_items: "{{ dotfiles_files }}"