---
- name: Ensures ~/.ssh/ directory exists
  file:
    path: "~/.ssh"
    state: directory

- name: Ensure that ssh rsa key is in the ~/.ssh/
  command : "ssh-keygen -q -t rsa -b 4096 -f ~/.ssh/key -C 'GlaIZier' -N ''"
  args:
    creates: "~/.ssh/key"

- name: Ensure the ssh config is copied
  copy:
    src: {{ dotfiles_repo_local_destination }}/general/ssh/config
    dest: ~/.ssh/config
  when: configure_dotfiles